In [2]:
import numpy as np

In [3]:
off_diag = np.ones([4, 4]) - np.eye(4)

In [4]:
off_diag

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.]])

In [8]:
np.where(off_diag)[0]

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [9]:
def encode_onehot(labels):
    classes = set(labels)
    classes_dict = {c: np.identity(len(classes))[i, :] for i, c in
                    enumerate(classes)}
    labels_onehot = np.array(list(map(classes_dict.get, labels)),
                             dtype=np.int32)
    return labels_onehot

In [18]:
encode_onehot(np.where(off_diag)[1])

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int32)

In [17]:
classes = set(np.where(off_diag)[0])

classes_dict = {c: np.identity(len(classes))[i, :] for i, c in
                    enumerate(classes)}
classes_dict

{0: array([1., 0., 0., 0.]),
 1: array([0., 1., 0., 0.]),
 2: array([0., 0., 1., 0.]),
 3: array([0., 0., 0., 1.])}

In [14]:
for i, c in enumerate(set(np.where(off_diag)[0])):
    print(i,c)

0 0
1 1
2 2
3 3


In [13]:
import numpy as np

num_variables = 4
sender_mask = np.zeros([num_variables-1, num_variables])
sender_mask[:,0]=1

for i in range(num_variables-1):
    temp = np.zeros([num_variables-1, num_variables])
    temp[:, i+1] = 1
    sender_mask = np.concatenate((sender_mask, temp))
    
receiver
sender_mask 

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [12]:
for i in range(num_variables-1):
    temp = np.zeros([num_variables-1, num_variables])
    temp[:, i+1] = 1
    sender_mask = np.concatenate((sender_mask, temp))
        
sender_mask 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [7]:
for i in range(num_variables-1):
    temp = np.zeros([num_variables-1, num_variables])
    temp[:, i+1] = 1

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
receiver_mask = np.eye(4)
np.delete(receiver_mask, 0,0)
    

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
    receiver_mask = np.eye(4)
    receiver_mask = np.delete(receiver_mask, (0), axis=0)
    
    for i in range(4-1):
        temp = np.eye(4)
        temp = np.delete(temp, (i+1), axis=0)
        receiver_mask = np.concatenate((receiver_mask, temp))

In [25]:
receiver_mask

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [2]:
import os
os.mkdir('../saved_model/dfd')